### ISSUE TITLE
[FEAT]: create `QueryParams` + `Data` for NEW `portfolio_analytics` function

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblDATA#27]
## Main Goal
Create a new function in humblDATA that pulls in and returns a row of data for each ticker. This should be vectorizsed to optimize when fetching multiple tickers.

## Tasks
 - [x] Create Query Params & Data standard models for `portfolio_analytics`
        Fields of Data:
        - ticker
        - last close
        - Mandelbrot_channel
        - up/down
        - R/R
        - asset class
        - sector
        - momentum
        - trend
        - humblSuggestion
    - [x] Add `user_table()` to `Portfolio()` class
        - This function should gather all required information asynchronously/concurrently
    - [x] Collect the sector and asset class for each symbol
        - [x]  correctly filter all stocks to their asset class and sector from the choices
        - [ ] 
    - [x] collect statistics about Mandelbrot range vs current (upside/downside/ratio)
    - [ ] add momentum and trend calculation (3m ROC vs 1/3yr ROC )
