### ISSUE TITLE
[TESTING]: add tests for `openbb_helpers.py`

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblDATA#38]
# Main Goal
I need to add tests for `openbb_helpers.py`

# Tasks

- [ ] Mock API calls to `obb.equity.price.quote` for `aget_latest_price()`
- [ ] Mock API calls to `obb.equity.profile` for `aget_equity_sector()`
- [ ] Mock API calls to `obb.equity.etf.info` for `aget_etf_sector()`

**Comment by iKoles-dev** [comment]
Submitted PR #60 for this bounty: https://github.com/humblFINANCE/humblDATA/pull/60

It replaces the stale skipped OpenBB helper tests with active mocked async API-client coverage for `aget_latest_price`, `aget_equity_sector`, and `aget_etf_category`, without making real OpenBB/API calls. The added latest-price edge-case test also exposed and fixes the quote query-param schema so unsupported providers can be omitted as `aget_latest_price()` already intends.

Verification:
- `uv run --frozen pytest tests/unittests/core/test_openbb_helpers.py`
- `uv run --frozen pytest tests/test_import.py tests/test_cli.py tests/unittests/core/test_openbb_helpers.py`
- `uv run --frozen --group test ruff check tests/unittests/core/test_openbb_helpers.py src/humbldata/core/standard_models/openbbapi/EquityPriceQuoteQueryParams.py`
- `uv run --frozen --group test ruff format --check tests/unittests/core/test_openbb_helpers.py src/humbldata/core/standard_models/openbbapi/EquityPriceQuoteQueryParams.py`
- `uv run --frozen python -m py_compile tests/unittests/core/test_openbb_helpers.py src/humbldata/core/standard_models/openbbapi/EquityPriceQuoteQueryParams.py`
- `git diff --check`
